### ISSUE TITLE
Delete file with read and/or write permission return wrong error message

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-stor#260]
**Steps**
        **Test Scenario:**
        #. Create random file
        #. Create a new namespace as a master user.
        #. Send an invitation to the slave user and accept it.
        #. Upload the file as a master user.
        #. Try to delete the file as a slave user and check the result.
        """

**Actual result**
```bash
'time="2017-09-28T15:42:13+02:00" level=error msg="fail to read metadata: key not found in etcd"\nfail to delete file: key not found in etcd\n'****
```

**Expected result**
Not valid access.

**Server**
e276bd02c7a691ae48a51885c0f63b84bf37411c

**Client**
e276bd02c7a691ae48a51885c0f63b84bf37411c

**Comment by katia-e** [comment]
I tried to reproduce the error using the instructions above. I was uploading a file with master and deleting with slave and also tried all other combinations. Every time the file was deleted successfully.

**Comment by GlenDC** [comment]
@islamTaha12 can you verify if his issue is still unresolved, as I'm suspicious about bugs simply resolving themselves magically.

Also @katia-e next time when working on an issue like this, ensure that there is a unit and/or end-to-end test is available, which reproduces the reported procedure in a way that would for sure trigger the bug if it would exist. Also ensure that all components used in that end-to-end test are properly unit-tested and add unit-tests where they are missing.

**Comment by katia-e** [comment]
@islamTaha12, @GlenDC  when I was testing I did not use python automated test even though the test is there, I did it manually. I would need some introduction in automated tests in order to use it. I was told there were some updates in code at 0-store some time ago, that might have resolved this problem, that is why the bug could disappear. @islamTaha12, please let me know if the error is still reproduced with the automated test, then I will continue with it.

**Comment by islamTaha12** [comment]
@katia-e here is the testsuite doc
https://github.com/zero-os/0-stor/tree/master/test

**Comment by islamTaha12** [comment]
There is an error in ""give member permission failed: code=409, err=invalid character 'C' looking for beginning of value\n"" so, we are blocked till @zaibon  regenerate the IYO client and see if its better handled now

```bash
zerostorcli --conf /gopath/src/github.com/zero-os/0-stor/client/cmd/zerostorcli/config.yaml namespace set-acl --namespace xtremx_881 --userid ah-elsayed -w
```

**Comment by GlenDC** [comment]
> so, we are blocked till @zaibon regenerate the IYO client and see if its better handled now

@islamTaha12, created an issue for that on https://github.com/itsyouonline/identityserver/issues/675, not sure who'll fix it though, as I'm not involved in that repo.

Also @chrisvdg suggested that this 409 issue has already been fixed in 0-stor. Make sure to use your verified email, instead of username.

**Comment by islamTaha12** [comment]
@GlenDC Ya, It's working now using the mail address, but we have a new iyo issue related to accept the invitation. 
https://github.com/itsyouonline/identityserver/issues/676

**Comment by islamTaha12** [comment]
@GlenDC 
I still have the same error:
```
'time="2017-11-28T12:23:34+02:00" level=error msg="fail to read metadata: key not found in etcd"\nfail to delete file: key not found in etcd\n'
```

Here is the test case to make sure that u are donig the same scenario
https://github.com/zero-os/0-stor/blob/master/test/test_suite/test_cases/basic_tests/test01_basic_tests.py#L106

**Comment by GlenDC** [comment]
@islamTaha12 why did you not say there was already a test available on master for the failure your reporting? As your steps to reproduce should in that case simply be: "run this test like this..." ...

Also, these tests are running on Travis right? So why are we never getting this issue in travis? Do you have to run the test suite many times, in order to get the issue, or what?

**Comment by islamTaha12** [comment]
@GlenDC  cause it fails, so normally we skip it and log the skipping issue number in the log.

**Comment by GlenDC** [comment]
What? That's really bad... That's not how you fix bugs. If it fails, it means something is wrong and it has to be fixed. Now it's skipped, and this bug has been open for months! Seriously...

You find it annoying that a test fails? Well... that's how it's supposed to be! It should be annoying, and it should never be in master, until that test gives a green light...

@zaibon please tell me this isn't normal...

**Comment by zaibon** [comment]
-___- no it is not. What's the point of skipping test? It's like accepting this bug exists. If we don't see any error in the tests for us, there is no bug.

Please unskip all tests

**Comment by GlenDC** [comment]
> Please unskip all tests

I wouldn't recommend for this to be done on master though, let's unskip them on some branch (will do it now), and we can than fix the bugs that are caught in those failed tests, on that branch. This way we can merge once those are fixed. Otherwise master will be red-lights for quite a while, for no good reason.

**Comment by GlenDC** [comment]
> let's unskip them on some branch (will do it now), and we can than fix the bugs that are caught in those failed tests

Ok there is only one test that is skipped, it turns out. And that is the one that fails for this test. You can find it on the branch: https://github.com/zero-os/0-stor/tree/unskip-tests

**Comment by GlenDC** [comment]
@islamTaha12 @zaibon...

Are these tests still running in Travis? Because travis still succeeds after removing that skip line. Also I checked the output (https://travis-ci.org/zero-os/0-stor/jobs/308800054), and I don't really see any output at all from those tests? And they seem to suspiciously fast (0.01s) o.O I have a feeling none of those tests are actually running? Can you confirm @islamTaha12?

**Comment by zaibon** [comment]
Now I remember these tests are not run for every commit. Because they take way to much time to deploy and execute. Need to be trigger manually. 

@islamTaha12 but I though we have a cron job that at least run them once a day or something??

**Comment by GlenDC** [comment]
@zaibon so what does that python thing do than in Travis? Nothing? Why do we even have it there than? Because it seems like 99.99% of the time spent on that job is simply installing dependencies and the environment, rather than an actual test.

**Comment by islamTaha12** [comment]
@zaibon @GlenDC First of all I need to clarify why we are SKIPPING test cases regarding to a bug. Actually, we are running the test suite and it produces a report which contains (success, fail and error) then we investigate in each (fail and error) test cases. If we find a bug, we report it and skip its test case till it is fixed otherwise we will spend another time in the next running investigating the same fail and reporting the same bug which doesn't make any sense. The next run may be green and it is meaning that this code version has no more new bugs except the already reported bugs. If the development team fix the bug and set the "verification" label on it, we will verify this bug and remove the skipping instruction from our test suite.

**Comment by islamTaha12** [comment]
@GlenDC The installation and the execution of this test suite won't be run except it is a cron job or manually triggered so I believe it doesn't consume any time in the normal cases.

https://github.com/zero-os/0-stor/blob/master/test/deploy_test_env/run_tests.sh#L75

**Comment by islamTaha12** [comment]
@zaibon We didn't configure a cron job.

**Comment by ramezsaeed** [comment]
Hello @zaibon & @GlenDC
in all projects we work on there are releases versions, and in order to release any version we need to have a green run on its branch, so we had to skip the failed tests as the related issues have fix versions in the comming releases and should be mentioned in release notes.
And also maybe sometimes we write new test cases for new features which is not implemented yet.
so thats simply why they added the skip feature in testing in general.
but ofcourse we can agree together how do you like to manage that.

@islamTaha12 how come we don't have a cron job for that, please add one asap

**Comment by islamTaha12** [comment]
@ramezsaeed Done

**Comment by islamTaha12** [comment]
@zaibon @ramezsaeed 
As we decided before the deployment script will create zeroOS machine then install 0-orchestrator, Actually we were using Maxium auto setup script to do that. Now, Maxium changed this script and merged it to the orch master so we need to update the deployment script then use Travis and I dont knw what is the status of orchestrator now cause we paused working in it a month ago I think.

My question is, Should I do this now or back to the previous installation approach which was totally independent on orchestrator?

**Comment by GlenDC** [comment]
Moving this to beta-3, as I really have no time to look into this, in the current state.

Either provide me with detailed (step-by-step) instructions how to trigger this "bug" manually, or provide me with detailed instructions how I can run the necessary automated test on my local OSX dev machine, because right now I fail to reproduce it both manually and automatically, due to not fully understanding all steps.

@islamTaha12...

**Comment by islamTaha12** [comment]
@GlenDC There is full description steps to execute the test suite using travis or local. 
https://github.com/zero-os/0-stor/blob/master/test/README.md

**Comment by GlenDC** [comment]
I do know that @islamTaha12, but on my MacOS machine your tests don't run at all, as you assume I work on a Linux (Debian?) machine AFAIK. I can't install, and even when I try installing those dependencies manually things don't run as I don't have the same versions as you assume we have.

These tests really shouldn't be written in python at all anyhow... I really want something that I can run with one click of a button and much easier than the ones currently are. It should also work on all platforms that our code support (e.g Linux, MacOS, Windows), as we have developers working on all 3 of those OS (families).

**Comment by elafont** [comment]
I did a by hand test of this error and I got exactly the same result previewed by Islam. In fact I got other IYO related issues.
What I did

1.- Setup 2 etcd servers (localhost:{2380,2390})
2.- Setup 3 zstordb servers (localhost:{12345,12346,12347})
3.- Setup Account on IYO for User1, organization: test260, namespace: ns260
4.- Setup Account on IYO for User2, no organization,no namespace
5.- Create config files, one for User1 and another one for User2, no encryption, no compression
6.- Verified permissions 
```
$ bin/zstor namespace permission get User2 ns260  -C configUser1.yaml
Read: false
Write: false
Delete: false
Admin: false

$ bin/zstor namespace permission get User1  ns260 -C configUser1.yaml
Read: true
Write: true
Delete: true
Admin: true
```
7.- Created namespace t260
```
$ bin/zstor namespace create  t260 -C configUser1.yaml
INFO[0000] namespace "t260" created  
```
8.- Verified permissions 
```
$ bin/zstor namespace permission get User1  t260  -C configUser1.yaml
Read: true
Write: true
Delete: true
Admin: true
```
9.- Upload a file to the new namespace, using a modified zstor binary that let me change the namespace without editing the config file
```
$ bin/zstor -n t260 file upload aFile -C configUser1.yaml
INFO[0000] Setting namespace config to [t260]           
INFO[0000] data from "./aFile" uploaded as key = "aFile"
```
10.- Invited second user to the t260 namespace, gone to the IYO website as User 1 and invited User2
11.- Verify permissions for User2, before User2 has accepted the invitation
```
$ bin/zstor namespace permission get User2 t260 -C configUser1.yaml
Read: false
Write: false
Delete: false
Admin: true
```
**WHY does User2  have Admin rights if he has not yet accepted the invitation ?**
The permissions remains the same **After** User2 accepted the invitation

12.- Verify permissions for User2 
$ bin/zstor namespace permission get User2  t260 -C configUser2.yaml
Error: failed to retrieve permission for User2:t260: login failed:invalid response's status code :400
**Why can not retrieve the rights of User2 for namespace t260 ?**
User2 has been invited and accepted at namespace t260

13.- Remove the file from namespace t260 as User2
$ bin/zstor -n t260 file delete aFile  -C clientUser2.yaml
INFO[0000] Setting namespace config to [t260]           
Error: failed to delete file "aFile": failed to get access token, response code = 400

Seems right, as zstor is unable to get rights, but the error shown seems to indicate other problems

**Comment by elafont** [comment]
ConfigUser1.yaml
```
iyo:
  organization: test260
  app_id: otzMc8WXFwBqdfU_YiPiMQBgTkeU
  app_secret: S_ZiZNGWZOe_7ZzkTdbkmCV_ZiZp
namespace: ns260
datastor:
  shards:
    - 127.0.0.1:12345
    - 127.0.0.1:12346
    - 127.0.0.1:12347
  pipeline:
    block_size: 4096
    distribution:
      data_shards: 2
      parity_shards: 1
metastor:
  db:
    endpoints:
      - 127.0.0.1:2380
      - 127.0.0.1:2390
```

ConfigUser2.yaml
```
iyo:
  organization: test260
  app_id: UH9WSWpo9aKqPtNWvWV9PPJpt
  app_secret: Oan_qTZl-9nGstgwEXuQelSE2y1K
datastor:
  shards:
    - 127.0.0.1:12345
    - 127.0.0.1:12346
    - 127.0.0.1:12347
  pipeline:
    block_size: 4096
    distribution:
      data_shards: 2
      parity_shards: 1
metastor:
  db:
    endpoints:
      - 127.0.0.1:2380
      - 127.0.0.1:2390
```

**Comment by GlenDC** [comment]
> WHY does User2 have Admin rights if he has not yet accepted the invitation ? The permissions remains the same After User2 accepted the invitation

That question and observation is one and the same. I suppose the permissions are simply already applied, even if not accepting. While not ideal, i don't think this is ever a super big issue. Has to be resolved none the less, but really nothing that would cause us issues at this point.

> Why can not retrieve the rights of User2 for namespace t260 ?

that's a bug for sure, and I'm fairly sure its a bug coming from the IYO side, unless I'm missing something in our codebase

**Comment by GlenDC** [comment]
@lafont-e any more news/info for this issue, now that some other issues have been fixed?

**Comment by lafont-e** [comment]
this issue has 2 variants
a) the  permissions for IYO guest users, it's designed this way, a guest can not know his permissions, so nothing to do here, as you know IYO team needs to fix it.
b) Delete failed mostly because GET method was used instead of the DELETE, that was solved in  #480

There is something more to fix here I'm not aware ?

**Comment by GlenDC** [comment]
No that looks acceptable. Closing this issue in that case.
